[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
opacity = 0.9
dynamic_padding = true
decorations = "Full"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 12.5

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true
blink_interval = 750
blink_timeout = 5

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[shell]
program = "/home/shoney/dotfiles/bin/tmux-main.sh"


[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
